(function(){
'use strict';
var managementBase='/v0/management/plugins/credential-tier-router';
var key='';
var current={settings:null,plan:{credentials:[],changes:0,unknown:0},history:[]};
var tierLabels={primary:'Primary',regular:'Regular',backup:'Backup',paused:'Paused'};
var strategyLabels={quota_bands:'Quota bands',balanced:'Balanced rotation',reset_soon:'Reset soon first',manual:'Manual tiers'};
var demo=new URLSearchParams(location.search).get('demo')==='1';
function byId(id){return document.getElementById(id)}
function escapeHTML(value){return String(value==null?'':value).replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]})}
function applyResolvedTheme(theme,background){var root=document.documentElement;if(theme==='light')root.removeAttribute('data-theme');else root.setAttribute('data-theme',theme);root.style.backgroundColor=background||themeBackground(theme);root.style.colorScheme=theme==='dark'?'dark':'light'}
function themeBackground(theme){return theme==='dark'?'#151412':theme==='white'?'#fff':'#faf9f5'}
function readCPATheme(){try{if(window.parent===window)return null;var root=window.parent.document.documentElement,theme=root.getAttribute('data-theme'),background=window.parent.getComputedStyle(root).getPropertyValue('--bg-secondary').trim();return {theme:theme==='dark'||theme==='white'?theme:'light',background:background}}catch(_){return null}}
function initTheme(){var parent=readCPATheme();if(parent){applyResolvedTheme(parent.theme,parent.background);try{new MutationObserver(function(){var next=readCPATheme();if(next)applyResolvedTheme(next.theme,next.background)}).observe(window.parent.document.documentElement,{attributes:true,attributeFilter:['data-theme','style','class','lang']})}catch(_){}return}var media=window.matchMedia&&window.matchMedia('(prefers-color-scheme:dark)');function sync(){applyResolvedTheme(media&&media.matches?'dark':'white')}sync();if(media&&media.addEventListener)media.addEventListener('change',sync)}
function xorBytes(bytes,keyBytes){var output=new Uint8Array(bytes.length);for(var i=0;i<bytes.length;i++)output[i]=bytes[i]^keyBytes[i%keyBytes.length];return output}
function decodeCPAStorage(raw){if(!raw)return null;var prefix='enc::v1::',text=raw;if(text.indexOf(prefix)===0){var binary=atob(text.slice(prefix.length)),bytes=new Uint8Array(binary.length);for(var i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);var storageKey='cli-proxy-api-webui::secure-storage|'+location.host+'|'+navigator.userAgent;text=new TextDecoder().decode(xorBytes(bytes,new TextEncoder().encode(storageKey)))}return JSON.parse(text)}
function readCPAKey(){try{var parsed=decodeCPAStorage(localStorage.getItem('cli-proxy-auth')),state=parsed&&parsed.state?parsed.state:parsed,value=state&&state.managementKey;return typeof value==='string'?value.trim():''}catch(_){return ''}}
function showConnectionNotice(message){byId('connectionMessage').textContent=message;byId('connectionNotice').hidden=false;byId('app').setAttribute('aria-busy','false')}
function hideConnectionNotice(){byId('connectionNotice').hidden=true}
async function api(path,options){options=options||{};options.headers=Object.assign({'Authorization':'Bearer '+key},options.headers||{});var response=await fetch(managementBase+path,options);var payload=await response.json().catch(function(){return {error:'CPA returned an invalid response'}});if(!response.ok)throw new Error(payload.error||('Request failed: HTTP '+response.status));return payload}
function demoState(){var now=Date.now();return {plugin_status:'ready',settings:{auto_apply:true,strategy:'quota_bands',interval_minutes:15,providers:['codex','antigravity'],antigravity_group:'gemini',failure_threshold:3,manual_tiers:{}},next_probe_at:new Date(now+12*60000).toISOString(),plan:{generated_at:new Date().toISOString(),strategy:'quota_bands',changes:2,unknown:1,credentials:[
{provider:'codex',account:'pr•••••@example.com',auth_index:'codex-a',current_tier:'regular',proposed_tier:'primary',reason:'At least 50% quota remaining',quota:{remaining:84,reset_at:new Date(now+5*86400000).toISOString(),status:'ready'},changed:true},
{provider:'codex',account:'ba•••••@example.com',auth_index:'codex-b',current_tier:'primary',proposed_tier:'regular',reason:'20%–49% quota remaining',quota:{remaining:36,reset_at:new Date(now+2*86400000).toISOString(),status:'ready'},changed:true},
{provider:'antigravity',account:'ag•••01@example.com',auth_index:'ag-a',current_tier:'primary',proposed_tier:'primary',reason:'At least 50% quota remaining',quota:{remaining:68,reset_at:new Date(now+8*3600000).toISOString(),status:'ready'},changed:false},
{provider:'antigravity',account:'ag•••02@example.com',auth_index:'ag-b',current_tier:'backup',proposed_tier:'backup',reason:'Using the previous quota; latest check failed once',quota:{remaining:12,reset_at:new Date(now+18*3600000).toISOString(),status:'cached',fail_count:1},changed:false},
{provider:'antigravity',account:'ag•••03@example.com',auth_index:'ag-c',current_tier:'regular',proposed_tier:'regular',reason:'Quota is temporarily unknown; keeping the current tier',quota:{status:'unknown',fail_count:3},changed:false}
]},history:[{at:new Date(now-15*60000).toISOString(),trigger:'Automatic scheduling',summary:'Updated 2 credentials; new priorities mainly affect future requests',changes:2,errors:0},{at:new Date(now-30*60000).toISOString(),trigger:'Manual apply',summary:'Quota check complete; no credentials need changes',changes:0,errors:0}]}}
function showStatus(message){var node=byId('liveStatus');node.textContent=message;node.classList.add('visible');clearTimeout(showStatus.timer);showStatus.timer=setTimeout(function(){node.classList.remove('visible')},2800)}
function setBusy(busy,label){document.querySelectorAll('#previewButton,#applyButton,#refreshButton').forEach(function(button){button.disabled=busy});byId('app').setAttribute('aria-busy',busy?'true':'false');if(label)showStatus(label)}
function setStrategy(value){current.settings.strategy=value;document.querySelectorAll('.strategy-card').forEach(function(card){card.setAttribute('aria-checked',card.dataset.strategy===value?'true':'false')});renderRows();renderSummary()}
function readSettings(){var providers=Array.from(document.querySelectorAll('.provider-choice input:checked')).map(function(input){return input.value});var manual=Object.assign({},current.settings.manual_tiers||{});document.querySelectorAll('.manual-select').forEach(function(select){manual[select.dataset.authIndex]=select.value});return {auto_apply:byId('autoApply').checked,strategy:current.settings.strategy,interval_minutes:Number(byId('intervalMinutes').value),providers:providers,antigravity_group:byId('antigravityGroup').value,failure_threshold:Number(byId('failureThreshold').value),manual_tiers:manual}}
function applySettingsToControls(){var settings=current.settings;byId('autoApply').checked=!!settings.auto_apply;byId('intervalMinutes').value=String(settings.interval_minutes||15);byId('failureThreshold').value=String(settings.failure_threshold||3);byId('antigravityGroup').value=settings.antigravity_group||'gemini';document.querySelectorAll('.provider-choice input').forEach(function(input){input.checked=(settings.providers||[]).indexOf(input.value)>=0});setStrategy(settings.strategy||'quota_bands')}
function quotaCell(quota){quota=quota||{};if(quota.remaining==null){var label=quota.status==='retrying'?'Retrying':'Quota unknown';return '<span class="quota-status">'+label+'</span>'}var value=Math.max(0,Math.min(100,Number(quota.remaining))),klass=value===0?' empty':value<20?' low':'';return '<div class="quota-wrap"><div class="quota-track" role="progressbar" aria-label="Remaining quota" aria-valuemin="0" aria-valuemax="100" aria-valuenow="'+value+'"><div class="quota-fill'+klass+'" style="width:'+value+'%"></div></div><span class="quota-text">'+value+'%</span></div>'}
function formatReset(value){if(!value)return '—';var date=new Date(value);if(Number.isNaN(date.getTime()))return '—';var delta=date-Date.now();if(delta>0&&delta<86400000)return Math.max(1,Math.round(delta/3600000))+' hours from now';return date.toLocaleString('en-US',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
function tierBadge(tier){return '<span class="tier-badge '+tier+'">'+(tierLabels[tier]||tier)+'</span>'}
function filteredCredentials(){var provider=byId('providerFilter').value,tier=byId('tierFilter').value,health=byId('healthFilter').value;return (current.plan.credentials||[]).filter(function(item){var q=item.quota||{},status=q.status==='retrying'?'unknown':q.status;return (provider==='all'||item.provider===provider)&&(tier==='all'||item.proposed_tier===tier)&&(health==='all'||status===health)})}
function renderRows(){var rows=byId('accountRows'),items=filteredCredentials(),manual=current.settings.strategy==='manual';byId('accountCount').textContent=items.length+' accounts';if(!items.length){rows.innerHTML='<tr><td class="empty" colspan="7">No accounts match the current filters</td></tr>';return}rows.innerHTML=items.map(function(item){var currentTier=tierBadge(item.current_tier),proposed=item.changed?'<span class="tier-arrow">→</span>'+tierBadge(item.proposed_tier):'';var quota=item.quota||{},reason=item.reason||'';if(quota.status==='cached')reason='Using the previous quota; consecutive failures: '+(quota.fail_count||1);if(quota.status==='unknown')reason='Quota unknown; consecutive failures: '+(quota.fail_count||0);var options=['primary','regular','backup','paused'].map(function(tier){var selected=((current.settings.manual_tiers||{})[item.auth_index]||item.proposed_tier)===tier?' selected':'';return '<option value="'+tier+'"'+selected+'>'+tierLabels[tier]+'</option>'}).join('');return '<tr><td class="account-cell"><strong>'+escapeHTML(item.account)+'</strong><small>Credential details masked</small></td><td><span class="provider-badge">'+(item.provider==='codex'?'Codex':'Antigravity')+'</span></td><td>'+quotaCell(quota)+'</td><td>'+formatReset(quota.reset_at)+'</td><td>'+currentTier+proposed+'</td><td class="reason">'+escapeHTML(reason)+'</td><td><select class="manual-select" data-auth-index="'+escapeHTML(item.auth_index)+'" '+(manual?'':'disabled')+' aria-label="'+escapeHTML(item.account)+' manual tier">'+options+'</select></td></tr>'}).join('');document.querySelectorAll('.manual-select').forEach(function(select){select.addEventListener('change',function(){current.settings.manual_tiers=current.settings.manual_tiers||{};current.settings.manual_tiers[select.dataset.authIndex]=select.value;renderSummary()})})}
function renderMetrics(){var credentials=current.plan.credentials||[],active=credentials.filter(function(item){return !item.disabled&&!item.unavailable}).length,primary=credentials.filter(function(item){return item.proposed_tier==='primary'}).length,backup=credentials.filter(function(item){return item.proposed_tier==='backup'}).length,unknown=credentials.filter(function(item){var s=(item.quota||{}).status;return s==='unknown'||s==='retrying'||item.unavailable}).length;byId('activeMetric').textContent=active;byId('primaryMetric').textContent=primary;byId('backupMetric').textContent=backup;byId('unknownMetric').textContent=unknown;var codex=credentials.filter(function(i){return i.provider==='codex'}).length,ag=credentials.filter(function(i){return i.provider==='antigravity'}).length;byId('activeDetail').textContent='Codex '+codex+' · Antigravity '+ag;byId('nextProbeDetail').textContent='Next check: '+(current.next_probe_at?formatReset(current.next_probe_at):'Disabled')}
function renderHistory(){var root=byId('historyList'),history=current.history||[];if(!history.length){root.innerHTML='<div class="empty-block">No recent activity</div>';return}root.innerHTML=history.map(function(item){return '<article class="history-item"><div><strong>'+escapeHTML(item.trigger)+'</strong><p>'+escapeHTML(item.summary)+'</p></div><time>'+new Date(item.at).toLocaleString('en-US')+'</time></article>'}).join('')}
function renderSummary(){var changes=Number(current.plan.changes||0);if(current.settings.strategy==='manual'){var manualCount=Object.keys(current.settings.manual_tiers||{}).length;byId('changeSummary').textContent=manualCount?'Manual tiers set for '+manualCount+' accounts':'Select a tier for each account';return}byId('changeSummary').textContent=changes?'Preview will change '+changes+' credentials':'No tier changes in this preview'}
function render(){applySettingsToControls();renderMetrics();renderRows();renderHistory();renderSummary();byId('app').setAttribute('aria-busy','false')}
async function load(){setBusy(true,'Loading credential status');try{current=demo?demoState():await api('/state');render();showStatus('Credential status updated')}finally{setBusy(false)}}
async function connectFromCPA(){key=readCPAKey();if(!key){showConnectionNotice('Return to CPA Management, sign in with “Remember password” enabled, then refresh this page.');return}try{await load();hideConnectionNotice()}catch(error){key='';showConnectionNotice(error.message+'. Return to CPA Management, sign in with “Remember password” enabled, then refresh this page.')}}
async function preview(){current.settings=readSettings();setBusy(true,'Checking quota and preparing preview');try{if(demo){var sample=demoState();sample.settings=current.settings;current=sample}else{await api('/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(current.settings)});current.plan=await api('/preview')}render();showStatus('Preview complete; no credentials changed')}catch(error){showStatus(error.message)}finally{setBusy(false)}}
async function apply(){current.settings=readSettings();setBusy(true,'Saving settings and applying tiers');try{if(demo){current.plan.credentials.forEach(function(item){item.current_tier=item.proposed_tier;item.changed=false});current.plan.changes=0}else{await api('/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(current.settings)});current.plan=await api('/apply',{method:'POST'});var refreshed=await api('/state');current.history=refreshed.history;current.next_probe_at=refreshed.next_probe_at}render();showStatus('Settings saved and tiers applied')}catch(error){showStatus(error.message)}finally{setBusy(false)}}
function bind(){document.querySelectorAll('.strategy-card').forEach(function(card,index,cards){card.addEventListener('click',function(){setStrategy(card.dataset.strategy)});card.addEventListener('keydown',function(event){if(event.key!=='ArrowRight'&&event.key!=='ArrowLeft')return;event.preventDefault();var next=(index+(event.key==='ArrowRight'?1:-1)+cards.length)%cards.length;cards[next].focus();setStrategy(cards[next].dataset.strategy)})});['providerFilter','tierFilter','healthFilter'].forEach(function(id){byId(id).addEventListener('change',renderRows)});byId('historyToggle').addEventListener('click',function(){var panel=byId('historyPanel'),next=panel.hidden;panel.hidden=!next;this.setAttribute('aria-expanded',next?'true':'false')});byId('refreshButton').addEventListener('click',preview);byId('previewButton').addEventListener('click',preview);byId('applyButton').addEventListener('click',apply);byId('retryConnection').addEventListener('click',connectFromCPA)}
initTheme();bind();if(demo){load()}else{connectFromCPA()}
})();
